[ALPS08490829] remove the use of dma_buf lock
commit 28743e25fa1c ("dma-buf: Remove obsoleted internal lock")
removes the internal lock from dma_buf, so follow it to remove
the use of lock lock to fix the following errors:

vendor/mediatek/kernel_modules/mtkcam/mtk-aie/mem/aie_videobuf2-dma-contig.c:285:43: error: no member named lock in struct dma_buf
        struct mutex *lock = &db_attach->dmabuf->lock;
                              ~~~~~~~~~~~~~~~~~  ^
vendor/mediatek/kernel_modules/mtkcam/mtk-aie/mem/aie_videobuf2-vmalloc.c:265:43: error: no member named lock in struct dma_buf
        struct mutex *lock = &db_attach->dmabuf->lock;
                              ~~~~~~~~~~~~~~~~~  ^
vendor/mediatek/kernel_modules/mtkcam/mtk-dpe/isp_7sp/videobuf2-dma-contig.c:289:43: error: no member named lock in struct dma_buf
        struct mutex *lock = &db_attach->dmabuf->lock;
                              ~~~~~~~~~~~~~~~~~  ^
vendor/mediatek/kernel_modules/mtkcam/mtk-dpe/isp_7s/videobuf2-dma-contig.c:289:43: error: no member named lock in struct dma_buf
        struct mutex *lock = &db_attach->dmabuf->lock;
                              ~~~~~~~~~~~~~~~~~  ^

MTK-Commit-Id: bfb75c3e27199f5e98a41baa8460aaae7b333e68

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: If5eb780e49e8135824832e89888f1c5244f00d42